/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2017-09-01 05:35:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    pageEncoding=\"ISO-8859-1\"%>\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"easyui/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link id=\"themelink\" rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/black/easyui.css\">   \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/icon.css\">   \r\n");
      out.write("<script type=\"text/javascript\" src=\"easyui/jquery.min.js\"></script>   \r\n");
      out.write("<script type=\"text/javascript\" src=\"easyui/jquery.easyui.min.js\"></script>  \r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\">   \r\n");
      out.write("    <div data-options=\"region:'north',split:true\" style=\"height:80px;\">\r\n");
      out.write("    \t<div id=\"logo\">\r\n");
      out.write("    \t\t<img src=\"images/timg.jpg\">\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t\r\n");
      out.write("    \t<div id=\"Logindiv\" style=\"position:absolute;right:20px;top:20px;\">\r\n");
      out.write("    \t\t欢迎您，【超级管理员】！\r\n");
      out.write("    \t\t <a href=\"javascript:void(0)\" id=\"mb\" class=\"easyui-menubutton\"     \r\n");
      out.write("       \t\t\t\t\t data-options=\"menu:'#mm',iconCls:'icon-edit'\">Edit</a>   \r\n");
      out.write("\t\t  \t\t  <div id=\"mm\" style=\"width:150px;\">   \r\n");
      out.write("\t\t\t\t\t    <div >default</div> \r\n");
      out.write("\t\t\t\t\t    <div >black</div>\r\n");
      out.write("\t\t\t\t\t    <div >gray</div>\r\n");
      out.write("\t\t\t\t\t    <div >icons</div>\r\n");
      out.write("\t\t\t\t\t    <div >material</div>  \r\n");
      out.write("\t\t\t\t\t    <div >bootstrap</div> \r\n");
      out.write("\t\t\t\t\t</div>  \r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>   \r\n");
      out.write("    <div data-options=\"region:'south',split:true\" style=\"height:30px;\">\r\n");
      out.write("    \t<div style=\"text-align: center;\">\r\n");
      out.write("    \t 版权所有，翻版必究！\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>   \r\n");
      out.write("       \r\n");
      out.write("    <div data-options=\"region:'west',title:'West',split:true\" style=\"width:200px;\">\r\n");
      out.write("    \t\r\n");
      out.write("    </div>   \r\n");
      out.write("    <div data-options=\"region:'center',title:'center title'\" style=\"padding:5px;background:#eee;\">\r\n");
      out.write("\t\t  \t\t\r\n");
      out.write("    </div>   \r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    //\t$(function(){\r\n");
      out.write("    \t\t$(\"#mm\").menu({\r\n");
      out.write("    \t\t\tonClick:function(item){\r\n");
      out.write("    \t\t\t\t//alert(item.text);\r\n");
      out.write("    \t\t\t\tvar themename = item.text;\r\n");
      out.write("    \t\t//\tvar href = $(\"#themelink\").attr(\"href\");\r\n");
      out.write("    \t\t\tvar href=\"easyui/themes/\"+themename+\"/easyui.css\";\r\n");
      out.write("    \t\t\t$(\"#themelink\").val(\"href\",href);\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t})\r\n");
      out.write("    //\t})\r\n");
      out.write("    </script>\r\n");
      out.write("</body> \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
